# Site settings
title: CuriousCaloo
email: pascal.brokmeier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Blog about youth, student life, traveling, software engineerig, live experiences, photography and psychology. From AngularJS and the Internet of Things through Italy and Germany, swinging by techno parties and exploring down under, this blog really has a lot to offer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://curiouscaloo.com" # the base hostname & protocol for your site
twitter_username: PascalBrokmeier
github_username:  pascalwhoop
myname: Pascal Brokmeier

# Build settings
markdown: kramdown
disqus_username: pascalreiemkorb
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: "posts"   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts